#!/usr/bin/env python3
"""Regenerate assets/visitors-data.js from the GoatCounter API.

Runs in the Pages deploy workflow every few hours with GOATCOUNTER_TOKEN set
(an API key with "Read statistics"), so visitors.html stays a static page with
no key in it and no request to any service but the site itself.

Everything written here is already aggregated by GoatCounter: countries and
regions, referring sites, pages, browsers. No IP address or individual visit
is ever available through the API. Referrers are cut to their host name, so
a path copied from somebody's private link cannot end up on a public page.

    GOATCOUNTER_TOKEN=... python3 scripts/fetch_visitors.py [--since 2026-09-24]
"""
import argparse, datetime as dt, json, os, sys, time, urllib.error, urllib.parse, urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = 'https://jinleiphys.goatcounter.com'


def get(path, token, optional=False, **params):
    url = SITE + '/api/v0/' + path + '?' + urllib.parse.urlencode(params, doseq=True)
    req = urllib.request.Request(url, headers={
        'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json'})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            if e.code == 429:
                time.sleep(float(e.headers.get('X-Rate-Limit-Reset', 2)) + 0.5)
                continue
            if optional:  # a breakdown the site does not collect must not sink the run
                print('skipping %s: HTTP %d' % (path, e.code), file=sys.stderr)
                return {}
            sys.exit('GoatCounter %s -> HTTP %d: %s' % (path, e.code, e.read()[:200]))
    sys.exit('GoatCounter %s: still rate limited' % path)


def host(name):
    """'github.com/jinleiphys/FUSION' -> 'github.com'; generated names pass through."""
    return name.split('/')[0] if '.' in name.split('/')[0] else name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--since', default='2026-09-24', help='first day counted (UTC)')
    args = ap.parse_args()
    token = os.environ.get('GOATCOUNTER_TOKEN')
    if not token:
        sys.exit('GOATCOUNTER_TOKEN is not set')

    now = dt.datetime.now(dt.timezone.utc).replace(minute=0, second=0, microsecond=0) + dt.timedelta(hours=1)
    span = {'start': args.since + 'T00:00:00Z', 'end': now.strftime('%Y-%m-%dT%H:%M:%SZ')}

    total = get('stats/total', token, **span)
    hits = get('stats/hits', token, limit=30, **span)
    stat = lambda page, n: get('stats/' + page, token, optional=True, limit=n, **span).get('stats') or []
    # screen sizes come back with an empty name and the class in id ('phone', 'desktop', ...)
    named = lambda page, n: [[s.get('name') or s.get('id') or '', s['count']] for s in stat(page, n) if s['count']]

    countries = []
    for c in stat('locations', 60):
        regions = []
        if len(countries) < 8 and c.get('id'):
            regions = [[r['name'], r['count']]
                       for r in get('stats/locations/' + c['id'], token, optional=True, limit=12, **span).get('stats') or []
                       if r.get('name')]
        countries.append([c.get('id') or '', c['name'], c['count'], regions])

    refs = {}
    for r in stat('toprefs', 40):
        name = host(r.get('name') or '')
        if name == 'vibeinscience.com':  # moving between our own pages is not an arrival
            continue
        refs[name] = refs.get(name, 0) + r['count']

    data = {
        'updated': dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%dT%H:%MZ'),
        'since': args.since,
        'total': total.get('total', 0),
        'daily': [[d['day'], d.get('daily', 0)] for d in total.get('stats') or []],
        'pages': [[h['path'], h['count']] for h in hits.get('hits') or [] if not h.get('event')],
        'countries': countries,
        'refs': sorted(([k, v] for k, v in refs.items()), key=lambda kv: -kv[1]),
        'browsers': named('browsers', 8),
        'systems': named('systems', 8),
        'sizes': named('sizes', 6),
        'languages': named('languages', 10),
    }
    out = os.path.join(HERE, 'assets', 'visitors-data.js')
    with open(out, 'w') as f:
        f.write('/* generated by scripts/fetch_visitors.py; aggregate counts only */\n')
        f.write('const VISITORS=%s;\n' % json.dumps(data, ensure_ascii=False, separators=(',', ':')))
    print('%s: %d visitors, %d countries, %d referrers'
          % (out, data['total'], len(countries), len(data['refs'])))


if __name__ == '__main__':
    main()
