#!/usr/bin/env python3
"""Regenerate assets/world-dots.js, the dot-matrix world map of visitors.html.

A land grid on an equirectangular projection, every other row offset by half
a step so the dots pack hexagonally. Each dot carries the ISO 3166-1 alpha-2
code of the country it falls in, which is the code GoatCounter reports for a
visitor's location, so the page colours dots by joining on it.

Source: Natural Earth 1:10m admin-0 countries, China point of view (public
domain; 14 MB, not kept in the repository, pass it with --src):
  https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries_chn.geojson
In that edition Taiwan is part of the China polygon and the disputed Himalayan
boundaries follow the Chinese position. Hong Kong and Macao are separate
features there; they are folded into CN here, as are any TW visitors in
scripts/fetch_visitors.py, so the map, the tooltip and the lists agree.
ISO_A2 is -99 for France, Norway and Kosovo, so ISO_A2_EH is used.
Rings are thinned to ~0.05 degree before the point-in-polygon test; the
grid is 1.5 degrees, so nothing visible is lost.

Output, run-length encoded per row, plus a label point per country so that
territories too small for the grid (Singapore, Hong Kong, ...) still have a
place on the map:
  WORLD_DOTS = {step, lat1, nrow, ncol, codes: [...],
                runs: [[row, col0, len, codeIndex], ...], centers: {code: [lon, lat]}}

    python3 scripts/make_world_dots.py --src ne_10m_admin_0_countries_chn.geojson [--step 1.5]
"""
import argparse, json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Parts of China reported under their own ISO code.
FOLD = {'TW': 'CN', 'HK': 'CN', 'MO': 'CN'}

# Label points for territories too small for the grid; [lon, lat].
EXTRA_CENTERS = {
    'SG': [103.82, 1.35],
    'MT': [14.44, 35.9], 'LU': [6.13, 49.61], 'BH': [50.56, 26.07],
    'MU': [57.55, -20.25], 'MV': [73.5, 4.18], 'AD': [1.52, 42.51],
    'MC': [7.42, 43.74], 'LI': [9.55, 47.16], 'SM': [12.46, 43.94],
    'BB': [-59.54, 13.19], 'GU': [144.79, 13.44], 'RE': [55.54, -21.12],
}


def rings(geom):
    polys = [geom['coordinates']] if geom['type'] == 'Polygon' else geom['coordinates']
    return polys


def thin(ring, tol=0.05):
    out = [ring[0]]
    for p in ring[1:]:
        if abs(p[0] - out[-1][0]) + abs(p[1] - out[-1][1]) >= tol:
            out.append(p)
    return out if len(out) >= 4 else ring


def inside(x, y, poly):
    """Even-odd ray cast over the outer ring and its holes."""
    hit = False
    for ring in poly:
        n = len(ring)
        for i in range(n):
            x1, y1 = ring[i]
            x2, y2 = ring[(i + 1) % n]
            if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
                hit = not hit
    return hit


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True, help='ne_10m_admin_0_countries_chn.geojson')
    ap.add_argument('--step', type=float, default=1.5, help='grid step in degrees')
    ap.add_argument('--lat0', type=float, default=-56.0)
    ap.add_argument('--lat1', type=float, default=80.0)
    args = ap.parse_args()

    feats = json.load(open(args.src))['features']
    shapes, centers = [], dict(EXTRA_CENTERS)
    for f in feats:
        code = f['properties']['ISO_A2_EH']
        code = FOLD.get(code, code)
        if code != '-99' and code not in centers:
            centers[code] = [round(f['properties']['LABEL_X'], 2), round(f['properties']['LABEL_Y'], 2)]
        if code == 'AQ':
            continue
        for poly in rings(f['geometry']):
            poly = [thin(r) for r in poly]
            xs = [p[0] for p in poly[0]]; ys = [p[1] for p in poly[0]]
            shapes.append((code, min(xs), max(xs), min(ys), max(ys), poly))

    s = args.step
    ncol = int(round(360 / s))
    nrow = int(round((args.lat1 - args.lat0) / s)) + 1
    codes, index, runs, ndots = [], {}, [], 0
    for r in range(nrow):
        lat = args.lat1 - r * s
        off = 0.5 * s if r % 2 else 0.0
        cur = None
        for c in range(ncol):
            lon = -180 + off + c * s
            code = None
            for sc, x0, x1, y0, y1, poly in shapes:
                if x0 <= lon <= x1 and y0 <= lat <= y1 and inside(lon, lat, poly):
                    code = sc
                    break
            if code is None:
                cur = None
                continue
            if code not in index:
                index[code] = len(codes); codes.append(code)
            ci = index[code]
            ndots += 1
            if cur is not None and cur[3] == ci and cur[1] + cur[2] == c:
                cur[2] += 1
            else:
                cur = [r, c, 1, ci]
                runs.append(cur)

    out = os.path.join(HERE, 'assets', 'world-dots.js')
    with open(out, 'w') as f:
        f.write('/* generated by scripts/make_world_dots.py from Natural Earth 1:110m; do not edit */\n')
        f.write('const WORLD_DOTS=%s;\n' % json.dumps(
            {'step': s, 'lat1': args.lat1, 'nrow': nrow, 'ncol': ncol,
             'codes': codes, 'runs': runs, 'centers': centers}, separators=(',', ':')))
    print('%s: %d dots, %d countries, %d runs, %.0f kB'
          % (out, ndots, len(codes), len(runs), os.path.getsize(out) / 1024))


if __name__ == '__main__':
    main()
